apiVersion: v1
kind: Pod
metadata:
  name: test-master
  namespace: tsn-experiment
  labels:
    app: test-master
spec:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  containers:
  - name: sender
    image: python:3.11-slim
    command: ["sleep", "3600"]
